### ISSUE TITLE
mute changes to .ChartComposer-preferences.json

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#10]
As I use ChartComposer I get a little popup from Dropbox saying .ChartComposer-preferences.json has been changed. I believe there's a "mute" option to some of the Dropbox APIs. Could we mute these popups?

**Comment by elsigh** [comment]
in the meantime, there is the Dropbox App's preferences UI and you could uncheck "Edits"
![image](https://user-images.githubusercontent.com/517210/38636325-aea74cfa-3d7c-11e8-9df0-51005f44f5a4.png)

**Comment by elsigh** [comment]
I've unchecked "Edits to files" and my life is good now.

**Comment by stevesouders** [comment]
Added a FAQ. Closing.
