### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by davesyoung** [elsigh/chartcomposer#109]
I've started to play around with the screens someone sees in the early "empty" states of an app. 
TBH this is a little more focused on the True empty state where no one has shared content with you yet, but I can refine that. 

The main concept worth implementing at this point is the idea of a "Welcome" tab that is visible when in Guest Mode and disappears after you sign into dropbox.

![image](https://user-images.githubusercontent.com/306901/79380931-00f0a380-7f16-11ea-82cd-00d3ebe477d0.png)

In Figma here...
https://www.figma.com/file/aG6Z5XLNoKnD1ljFd5afDv/SongDocs-Getting-Started?node-id=358%3A50

ps, @elsigh  you can copy/paste links to specific screens by right clicking on a frame and going down to the copy/paste menu » Copy Link
![image](https://user-images.githubusercontent.com/306901/79380623-832c9800-7f15-11ea-921e-ce03fb033c02.png)

**Comment by elsigh** [comment]
Same design on Desktop, yeah? Do we have this graphic?

There's not a link to sign in as a guest here. Is that intentional? It's fine by me. 

There's currently a link to About and Home on our home screen but I'm thinking you left them off intentionally, yeah?

**Comment by davesyoung** [comment]
You mean there is no top-right profile image? 

Yeah, I don't think that is needed, all that stuff should just be under a hamburger menu on the left. 
I thought we were "Signing into guest" automatically as the default view, with a call to "Sign into Dropbox" as the way they view the files they have saved/received before. 

And yes the design on desktop is the same but just anchored to the left with a decent top and left margin.

On desktop in general I plan to move us from a three-pane to a two-pane window. That is either list and View, or edit and preview.
Thanks!

**Comment by elsigh** [comment]
I only sign you in as Guest if you come in with a share link or you click
Guest

**Comment by davesyoung** [comment]
Read up on brand guidelines, we are fine. They don't have specific guidelines for "Sign into Dropbox" we could use their logo on the button if we wanted to, but I tried and it looked a bit too cluttered and illegible anyway. 

It would be good to chat about why we should show a "logged out state" that isn't the guest state, I can't figure out the value of that... i feel we should just have the default state be the guest state with the calls to action leading them to sign into dropbox to save, delete, modify, or create content.

**Comment by elsigh** [comment]
RE signed-out vs Guest - We can build a default signed-out state that looks however you want for the most part, but we don't want to actually use dropbox's APIs unless there's an explicit action because bots/abuse etc.
