### ISSUE TITLE
two "new_song.pro" songs in list

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#15]
If I click "new song" twice, there are two "new_song.pro" items in the song list. That's confusing.

Maybe go to new_song_yymmddhhss.pro if "new_song.pro" is already there. We could try to do 1, 2, 3, 4, etc. but that's a pain and the timestamp might actually be helpful.

**Comment by elsigh** [comment]
Is this still an issue? I think my sync-on-load shoulda fixed this

**Comment by elsigh** [comment]
closing pre-emptively
