### ISSUE TITLE
URL to a specific song

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#16]
I'd kinda like to support a URL to a specific song. It could contain the Dropbox folder URL in the query string. What do we use as the song ID? Should it show all the folder's songs in the song list or just the single song? (I vote all songs.)

**Comment by elsigh** [comment]
I think we're good with this one now with the share link

**Comment by stevesouders** [comment]
Could we add a share link icon next to each song?

**Comment by stevesouders** [comment]
I tried putting a song's Dropbox link for the "share" parameter in the querystring and it didn't work.

**Comment by elsigh** [comment]
I don't think the share link works right now for just a single song, but for a folder..
Can you paste me link you're trying that doesn't work as intended?

**Comment by elsigh** [comment]
I was inferring from the original description that we might only support links to folders instead of single songs so if it's just that, I bet I can make it work for a single song pretty easily by just changing the function that gets called from parsing out the share url (e.g. using the one we use for the paste link input).

**Comment by elsigh** [comment]
hrm, no we already call `loadDropboxLink` from the `shareLink` so it must be something else not working correctly. I haven't been testing links to songs vs folders much lately so it could just be something else.

**Comment by stevesouders** [comment]
Here's the Dropbox link for To You Sweetheart Aloha. I chose this one because it doesn't have any image or audio directives (which would require folder access). 

https://www.dropbox.com/s/xvemcwkuhdfln0h/To%20You%20Sweetheart%20Aloha.pro?dl=0

If I URIencode that and append it to the share param here's the result:

https://chartcomposer.com/?share=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fxvemcwkuhdfln0h%2FTo%2520You%2520Sweetheart%2520Aloha.pro%3Fdl%3D0

The above link generates this error in console:
Failed to load resource: the server responded with a status of 409 (shared_link_not_found/..)

Sometimes you have to change dl=0 to raw=1:
https://chartcomposer.com/?share=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fxvemcwkuhdfln0h%2FTo%2520You%2520Sweetheart%2520Aloha.pro%3Fraw%3D1

But that link also fails with a similar error.
