### ISSUE TITLE
get x_chordposition: above nicer

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#21]
You can use this directive to put the chords above the lyrics:
    {x_chordposition: above}

It works pretty well except if you have three chords in a row: [A][A][A]

Also, it runs into the comments (like "Verse 1"). See Calamity song for examples of these problems.

I'm struggling with the CSS for this. Could you take a look?

**Comment by elsigh** [comment]
@stevesouders - would you mind if I rewrote the `exportHtml` function in `chordProParse` as a React component instead? I think it will make formatting easier and make `chordProParse` a more purely string to object sort of thing.

I think chordProParse needs to contain the source of truth re directives, but could expose them so I can switch/case in the renderer.

**Comment by elsigh** [comment]
My motivations here are to make use of `styled-jsx` (css syntax) as well as the flexibility to render the DOM differently based on `inline` vs `above`. I think position absolute for above is going to end up being a fool's game compared to lining up chords above characters at a particular position and I have been looking at an excuse to use React's portals(https://reactjs.org/docs/portals.html) feature which I think suits this case precisely.

I think it might also make sense for the `chordProParse` function to do certain things outside of the formatting steps (e.g. transpose seems ripe) and it might be nice to separate those to make testing easier later on.

**Comment by stevesouders** [comment]
I'm fine if you rewrite chordProParse.js. It's a low priority but it might help me get more in the React-frame-of-mind.

But for this bug I think it's just a matter of some CSS mojo. For example, I got it to work in my previous sheet music website:
http://stevesouders.com/sheetmusic/music.php?action=Song&song=calamity_song.the_decemberists.ugs697345

I can't figure out how to carry that over tho.

**Comment by elsigh** [comment]
It's true I can probably do it with css foo but right now with everything having inline styles or code branching it's a little tricky, so I figured it may as well make sense to rewrite. That said, the easy thing is just to convert the code to use CSS classNames and then add one `<style jsx global>` block in `SongView` and do all the CSS in there.

**Comment by stevesouders** [comment]
I agree that would be cleaner, but is that necessary to solve the problem?
