### ISSUE TITLE
Expose a cheat sheet of chordpro directives (autocomplete would rock too)

### ISSUE THREAD

**Issue by elsigh** [elsigh/chartcomposer#28]
I can never remember the directives.

**Comment by stevesouders** [comment]
What if we try to move away from people having to edit Chordpro. Instead, we could have some UI menus. For example, the "Insert" menu would contain:
- Audio File
- Video File
- Chorus
- Verse
- Comment

The "Edit" menu would contain:
- Text -> Color, Size, Font
- Chord -> Color, Size, Font
- Artist
- Composer
- Subtitle
- Title
- Capo

When you click those menu items and make selections we would automatically update the ChordPro text with the appropriate directives.

It might be awhile before we have a WYSIWYG editor and can get rid of the textarea. But the menus still work. Even if we have the textarea, you can still choose Edit -> Capo and pick "2" and see "{capo: 2}" in the textarea and "capo: 2" in the viewer.

**Comment by stevesouders** [comment]
closing but opened a new issue for a wysiwyg editor
