### ISSUE TITLE
Add song layout prefs (chord above words or inline, chord color, etc..)

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#3]
including chords inline or on top

also text & chord colour etc.

**Comment by stevesouders** [comment]
The important directives now work in that they actually affect the HTML preview. The directives that work that should be added to the prefs UI are:

- textcolour - can be a hex (#123456) or a "known colour" (eg, red, green, blue)
- textsize - It's supposed to be a number (like "14") but we also accept "120%" and "1.2em". You could just make this a string, but I recommend making it require an integer.
- textfont - Just a string.
- chordcolour|size|font - see above
- x_chordposition - inline, above (the "x_" means a custom (non-spec) directive)

Here's the spect for colour|size|font: http://www.chordpro.org/chordpro/Directives-props_text_legacy.html

Other prefs we might want to support some day:
- background color
- x_chorddiagramsize - none, small, medium, large
- x_chorddiagramposition - top, right, left, bottom
- x_instrument - guitar, bass, ukulele, mandolin - only important when we do chord diagrams or tablature
- x_header - let people put some HTML at the top
- x_footer - let people put some HTML at the bottom

**Comment by elsigh** [comment]
https://github.com/elsigh/chartcomposer/commit/944a534a5990ff6b8428c5a2bae1b5d460957ee9 implements this with selects - we can add more values as options.
I still need to make a change to enable the version that works nicely on phone layout.
