### ISSUE TITLE
owner can't edit songs with "Can View" share link

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#41]
1. Owner goes to Dropbox web UI and creates share link with "Can View"
2. Go to https://chartcomposer.com
3. Oauth with Owner Dropbox credentials
4. paste share link
5. can see SongEditor but edits are not saved

Either the owner should be able to make edits, or they should not see the SongEditor. It seems like the editor should _always_ be able to edit their own stuff. If not, image this scenario: I'm a music teacher so I need edit permissions on my folder but I need to give my kids view-only permission. How do I do that? The likely steps are the ones above, but those don't let me make edits.

**Comment by elsigh** [comment]
Is this irrelevant in a world with just choosing a db folder (and not pasting links)?

**Comment by stevesouders** [comment]
no - closing
