### ISSUE TITLE
scrollbar doesn't work in SongView

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#48]
Maybe it broke as part of adding the slider?

**Comment by elsigh** [comment]
Hrm, it works for me for my songs both locally and on chartcomposer.com

![image](https://user-images.githubusercontent.com/517210/39202200-12b6d480-47a6-11e8-82b2-64d312cda6f4.png)

Maybe it's some particular scenario?

**Comment by elsigh** [comment]
closing since I think it's working

**Comment by stevesouders** [comment]
This is my biggest bug-a-boo right now. I actually can't practice most of my songs. 

Let's choose a song that we can both see that has SongEditor and SongView. How about "Amazing Grace" in "Demo Songs"?

When I choose that I can scroll SongEditor but I can't scroll the SongView. Can you scroll SongView?

![image](https://user-images.githubusercontent.com/2819380/39276169-d0ec6b1c-489c-11e8-9b17-9008edcf5aef.png)

**Comment by elsigh** [comment]
`Amazing Grace` in Demo Songs isn't editable for me (as Guest) (who are you signed in as in your case?)

For me, if I open a song of mine, I can scroll both panes. Here I've got "Aeroplane over the sea" open and I can scroll both panes independently.. I wonder what on earth is going on.
But, what's most interesting and alarming (and you can see this from my screenshot) is that you seem to be seeing the newer version of our code (notice the lack of the Paste URL button) whereas I still have that button. Ugh.

![image](https://user-images.githubusercontent.com/517210/39277151-41957314-48a1-11e8-8277-674f4d5ebbb3.png)

Locally, where I am on master/HEAD I can scroll both panes independently as well.

Are there any errors in your JS console by chance? does it work locally?

**Comment by elsigh** [comment]
I'm calling this one fixed enough for now. I changed the UI to use toggle buttons in the header on desktop instead of our little arrow icons all over the place. =)
We can work on the resizer again later once we can debug.
