### ISSUE TITLE
add "Save" button for saving songs

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#54]
I just did a quick edit on 10+ songs (pasting "{duration: 200}") and only about half of them recorded the change. Opening the console I see that sometimes there's a 5-10 second lag before it gets saved. It'd be nice to have a "Save" button to make sure all changes were saved. 

Also, it would be nice if there was a better indicator that changes had _not_ yet been saved. Maybe replace the "saved 14 hours ago" message to "changes queued to be saved" (or something).

**Comment by elsigh** [comment]
Ah, it should still have saved them, even on the delay. It also writes the data all locally.. I think I can decrease the lag to like 2 seconds (I'd increased it thinking it would fix the cursor issue and forgot to change it back). And we could intercept Cmd-S to save on demand (I'd really like to not add another button in the UI). Would that work?

**Comment by elsigh** [comment]
I dropped the time down to 1s and I think we're probably good for now
