### ISSUE TITLE
replace Dropbox logo with ChartComposer icon

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#62]
I think the Dropbox logo isn't good for the hamburger menu icon. We now have stuff under there that isn't Dropbox (About, Help). It also makes us look like Dropbox. Later we might integrate with Google Drive. I think it'd be good to replace it with a ChartComposer icon.

Assigning to Lindsey as the more artistic person, but I might replace it with some notes if I can find good ones.

**Comment by elsigh** [comment]
I'm not sure which logo you're referring to?
We're using whatever your Dropbox profile picture is and maybe Dropbox uses a dropbox logo if you don't have one and that's what you're seeing? 
Here's what I have:
![image](https://user-images.githubusercontent.com/517210/45267409-86e66780-b420-11e8-950a-b1f8b2c0e3f6.png)

Or maybe you mean Guest mode?
