### ISSUE TITLE
directives are overwritten by prefs

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#77]
In the latest git pull, directives are ignored. Eg, if I do this in a song:
{chordcolour: blue}

That should override all other settings. But the latest code overrides these parsed directives with the preferences - which should not happen. Directives take precedence over prefs.

**Comment by stevesouders** [comment]
I moved the prefs around (see CVSNO) but not sure if that defeats something you were trying to do.

**Comment by elsigh** [comment]
I'm guessing you fixed this - my movement here had unintended consequences.
