### ISSUE TITLE
support read-only offline mode

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#81]
When I turn off wifi on my laptop and reload CC I get a "There is no internet connection" error. Nothing shows up in console.

**Comment by elsigh** [comment]
This looks like a way to try: https://github.com/hanford/next-offline

**Comment by elsigh** [comment]
Another approach: https://github.com/zeit/next.js/tree/master/examples/with-sw-precache

**Comment by elsigh** [comment]
ok!
with https://github.com/elsigh/chartcomposer/commit/6a4acbf92e777191f4da3ed32de8e8b44eae5abc we register a sw and then if you set chrome to offline and reload you get what you at least already got. There's not any UI indication that you're offline and so if you try to load songs you hadn't previously loaded the experience could be better, but still I'm calling this closed for now.

![image](https://user-images.githubusercontent.com/517210/43661205-420d7dfa-9716-11e8-9e52-d041c1f36eb3.png)
