### ISSUE TITLE
colors don't print - everything is b&w

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#82]

**Comment by stevesouders** [comment]
Actually - it looks like no colors are working: chords are black and "comment" gray background is missing.

**Comment by elsigh** [comment]
https://stackoverflow.com/questions/33410724/bootstrap-print-css-removes-background-color

**Comment by elsigh** [comment]
we load bootstrap for `react-bootstrap` components in `Meta.js` ala `<link rel="stylesheet" href="/static/bootstrap.min.css" />`
