### ISSUE TITLE
Song List: Add Flattened, sortable, searchable song list

### ISSUE THREAD

**Issue by elsigh** [elsigh/chartcomposer#98]
List should be sortable by:
* Song Asc (A-Z) [default]
* Artist Asc (A-Z)

Here's a mock
* not sure how easy/hard some aspects of this "Contacts" design exist as components in material-ui now, so we'll need to talk about scope of this if it's not a fairly easy out-of-the-box thing.

![image](https://user-images.githubusercontent.com/517210/78598025-5edd0700-7803-11ea-9bcc-930a32149fd7.png)

**Comment by LionDev93** [comment]
updatePreferences = preferences => {
    this.setState({ preferences });
    if (this.state.signedInAsGuest) {
      console.debug("Bail saving updatePreferences for guests");
      return;
    }

**Comment by LionDev93** [comment]
Hi, it's hard to manage project on upwork chat.
Can we use slack for managing project and payment on upwork?
my email: koalito.work@gmail.com

**Comment by elsigh** [comment]
One other bit here is that the tab chosen should be sticky like folders open/closed
